### ISSUE TITLE
Exact quote 3

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#53] opened 2016-10-11 11:06 UTC
Uploading photo failed thinking circle had strange blue lines around it

**Comment by Pikapangokev** [comment] 2016-10-11 11:22
![screen shot 2016-10-11 at 12 19 04](https://cloud.githubusercontent.com/assets/22468878/19268618/5b34b856-8fad-11e6-850d-a776d12d1520.png)

**Comment by neilpie** [comment] 2016-10-12 13:32
duplicate of #58

**Closed** 2016-10-12 13:33 UTC
Labels: duplicate
