### ISSUE TITLE
Updating exact quote with the price still sends 2 emails to client

### ISSUE THREAD

**Issue by Pikapangokev** [pie/PikaPango#129] opened 2016-11-14 19:40 UTC
![img_1467](https://cloud.githubusercontent.com/assets/22468878/20279876/378debec-aaa2-11e6-8289-8eeda9cfa927.jpg)

**Comment by neilpie** [comment] 2016-11-15 12:25
duplicate of #105

**Closed by neilpie** 2016-11-15 12:25 UTC
